### ISSUE TITLE
Improvements with potential to be merged upstream?

### ISSUE THREAD

**Issue by rainwoodman** [mludvig/mini-printf#11]
Thanks for making this amazing library public.

I included a variant of mini-printf as part of my tinypy fork:

https://github.com/rainwoodman/tinypy/commit/c4cae12f8b1fdfe7546a0f8d2ce6552bcb48a9d3

A few improvements:

1. an extension interface for outsource %o and %O to an external function. (under an ifdef, so this is optional) The interface is not thread-safe. So there is space to improve it; but we may want to allow stubbing out the entire buff interface if thread safety is already a concern.

2. always return the number of bytes would be written (excluding nul) even if that exceeds the size limit passed in. this is not posix though.
3. support for 'ld' 'lu', 'lx', 'lX' as long types.
4. padding of 's'.
5, padding to more than 9 chars and padding with space.

I am wondering if you are interested in merging some of these features. If so I'll prepare a PR.

**Comment by mludvig** [comment]
Hi, I no longer actively maintain mini-printf but if you send a PR and I may have a look at it. Cheers.

**Comment by rainwoodman** [comment]
Sure. Let's move to #12 .
